### ISSUE TITLE
Tormes: ERROR: could not find input file

### ISSUE THREAD

**Issue by Stigimoloch** [nmquijada/tormes#25]
Hi,
I have a problem with Tormes. When I work on fastq reads. When I start analysis all output files are moved by Tormes to rubbish and after in analysis I got a lot of information about "ERROR: could not find input file". In the end, I'm gotten empty folders without reports.
When I analyze the assembled genome in fasta format everything is ok. 
I'm looking forward to your answer.

error-tormes.txt
chmod: changing permissions of 'metadata.R': Operation not permitted
Software: /opt/anaconda3/envs/tormes-1.1/bin/abricate found
Software: /opt/anaconda3/envs/tormes-1.1/bin/convert found
Software: /opt/anaconda3/envs/tormes-1.1/bin/fasttree found
Software: /opt/anaconda3/envs/tormes-1.1/bin/kraken found
Software: /opt/anaconda3/envs/tormes-1.1/bin/kraken-report found
Software: /opt/anaconda3/envs/tormes-1.1/bin/megahit found
Software: /opt/anaconda3/envs/tormes-1.1/bin/mlst found
Software: /opt/anaconda3/envs/tormes-1.1/bin/parallel found
Software: /opt/anaconda3/envs/tormes-1.1/bin/prinseq-lite.pl found
Software: /opt/anaconda3/envs/tormes-1.1/bin/prokka found
Software: /opt/anaconda3/envs/tormes-1.1/bin/quast found
Software: /opt/anaconda3/envs/tormes-1.1/bin/roary found
Software: /opt/anaconda3/envs/tormes-1.1/bin/roary2svg.pl found
Software: /opt/anaconda3/envs/tormes-1.1/bin/sickle found
Software: /opt/anaconda3/envs/tormes-1.1/bin/spades.py found
Software: /opt/anaconda3/envs/tormes-1.1/bin/trimmomatic found
Software: /opt/anaconda3/envs/tormes-1.1/bin/../share/mauve-*/Mauve.jar found
Binaries for MAUVE found
Software: /opt/anaconda3/envs/tormes-1.1/bin/../CGE-modules/fimtyper/fimtyper.pl found
Software: /opt/anaconda3/envs/tormes-1.1/bin/../CGE-modules/serotypefinder/serotypefinder.py found
Binaries for BLAST version 2.6 or later found
Software: /opt/anaconda3/envs/tormes-1.1/bin/../CGE-modules/pointfinder/PointFinder.py found
chmod: changing permissions of '/media/bioinformatyka/Documents/roboczy_rafal/20200706_Tormes/EC5_out_test_fasq_8/metadata.R': Operation not permitted

Thanks for using tormes version 1.1
Status can be seen in "/media/bioinformatyka/Documents/roboczy_rafal/20200706_Tormes/EC5_out_test_fasq_8/tormes.log"

cp: cannot stat 'a': No such file or directory

Some reads are not gzipped... Let's gzip for optimize speed!

gzip: /media/bioinformatyka/Documents/roboczy_rafal/20200706_Tormes/EC5_out_test_fasq_8/Raw_reads/EC5_S11_L001_R2_001.fastq_R1.fastq.gz: Operation not permitted
gzip: /media/bioinformatyka/Documents/roboczy_rafal/20200706_Tormes/EC5_out_test_fasq_8/Raw_reads/EC5_S11_L001_R2_001.fastq_R1.fastq.gz: Operation not permitted
TrimmomaticPE: Started with arguments:
 -threads 20 -phred33 /media/bioinformatyka/Documents/roboczy_rafal/20200706_Tormes/EC5_out_test_fasq_8/Raw_reads/EC5_S11_L001_R2_001.fastq_R1.fastq.gz /media/bioinformatyka/Documents/roboczy_rafal/20200706_Tormes/EC5_out_test_fasq_8/Raw_reads/EC5_S11_L001_R2_001.fastq_R2.fastq.gz /media/bioinformatyka/Documents/roboczy_rafal/20200706_Tormes/EC5_out_test_fasq_8/cleaned_reads/EC5_S11_L001_R2_001.fastq.noadapt.R1.fastq.gz /dev/null /media/bioinformatyka/Documents/roboczy_rafal/20200706_Tormes/EC5_out_test_fasq_8/cleaned_reads/EC5_S11_L001_R2_001.fastq.noadapt.R2.fastq.gz /dev/null ILLUMINACLIP:/opt/anaconda3/envs/tormes-1.1/bin/../files/adapters.fasta:1:30:11
Using PrefixPair: 'AGATGTGTATAAGAGACAG' and 'AGATGTGTATAAGAGACAG'
Using PrefixPair: 'TACACTCTTTCCCTACACGACGCTCTTCCGATCT' and 'GTGACTGGAGTTCAGACGTGTGCTCTTCCGATCT'
Using Long Clipping Sequence: 'GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAG'
Using Long Clipping Sequence: 'TCGTCGGCAGCGTCAGATGTGTATAAGAGACAG'
Using Long Clipping Sequence: 'AGATCGGAAGAGCTCGTATGCCGTCTTCTGCTTG'
Using Long Clipping Sequence: 'AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTA'
Skipping duplicate Clipping Sequence: 'AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTA'
Using Long Clipping Sequence: 'AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCCGTATCATT'
Using Long Clipping Sequence: 'AGATCGGAAGAGCGGTTCAGCAGGAATGCCGAG'
Using Long Clipping Sequence: 'AGATCGGAAGAGCGGTTCAGCAGGAATGCCGAGACCGATCTCGTATGCCGTCTTCTGCTTG'
Using Long Clipping Sequence: 'TTTTTTTTTTAATGATACGGCGACCACCGAGATCTACAC'
Using Long Clipping Sequence: 'AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC'
Using Long Clipping Sequence: 'AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT'
Using Long Clipping Sequence: 'TTTTTTTTTTCAAGCAGAAGACGGCATACGA'
Skipping duplicate Clipping Sequence: 'AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC'
Using Long Clipping Sequence: 'GTGACTGGAGTTCAGACGTGTGCTCTTCCGATCT'
Using Long Clipping Sequence: 'TACACTCTTTCCCTACACGACGCTCTTCCGATCT'
Using Long Clipping Sequence: 'CTGTCTCTTATACACATCTCCGAGCCCACGAGAC'
Using Long Clipping Sequence: 'CAAGCAGAAGACGGCATACGAGATCGGTCTCGGCATTCCTGCTGAACCGCTCTTCCGATCT'
Using Long Clipping Sequence: 'CTGTCTCTTATACACATCTGACGCTGCCGACGA'
Using Long Clipping Sequence: 'AATGATACGGCGACCACCGAGATCTACACTCTTTCCCTACACGACGCTCTTCCGATCT'
ILLUMINACLIP: Using 2 prefix pairs, 17 forward/reverse sequences, 0 forward only sequences, 0 reverse only sequences
Exception in thread "main" java.io.FileNotFoundException: /media/bioinformatyka/Documents/roboczy_rafal/20200706_Tormes/EC5_out_test_fasq_8/Raw_reads/EC5_S11_L001_R2_001.fastq_R2.fastq.gz (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at org.usadellab.trimmomatic.fastq.FastqParser.parse(FastqParser.java:135)
	at org.usadellab.trimmomatic.TrimmomaticPE.process(TrimmomaticPE.java:268)
	at org.usadellab.trimmomatic.TrimmomaticPE.run(TrimmomaticPE.java:555)
	at org.usadellab.trimmomatic.Trimmomatic.main(Trimmomatic.java:80)
gzip: /media/bioinformatyka/Documents/roboczy_rafal/20200706_Tormes/EC5_out_test_fasq_8/cleaned_reads/*gz.gz: No such file or directory

ERROR: could not find input file "/media/bioinformatyka/Documents/roboczy_rafal/20200706_Tormes/EC5_out_test_fasq_8/cleaned_reads/EC5_S11_L001_R2_001.fastq.noadapt.R1.fastq".

Try 'perl prinseq-lite.pl -h' for more information.
Exit program.
gzip: /media/bioinformatyka/Documents/roboczy_rafal/20200706_Tormes/EC5_out_test_fasq_8/cleaned_reads/*fastq: No such file or directory
paste: /media/bioinformatyka/Documents/roboczy_rafal/20200706_Tormes/EC5_out_test_fasq_8/temp1: No such file or directory
cut: /media/bioinformatyka/Documents/roboczy_rafal/20200706_Tormes/EC5_out_test_fasq_8/kraken_summary.tmp: No such file or directory
cut: /media/bioinformatyka/Documents/roboczy_rafal/20200706_Tormes/EC5_out_test_fasq_8/kraken_summary.tmp: No such file or directory
sed: preserving permissions for ‘/media/bioinformatyka/Documents/roboczy_rafal/20200706_Tormes/EC5_out_test_fasq_8/sedXvpZWW’: Operation not permitted
sed: preserving permissions for ‘/media/bioinformatyka/Documents/roboczy_rafal/20200706_Tormes/EC5_out_test_fasq_8/mlst/sedyrBS9Y’: Operation not permitted
sed: preserving permissions for ‘/media/bioinformatyka/Documents/roboczy_rafal/20200706_Tormes/EC5_out_test_fasq_8/mlst/sedIVgKa0’: Operation not permitted

 WARNING: Pangenome analysis was skipped automatically due to low number of genomes to compare. 

sed: can't read /media/bioinformatyka/Documents/roboczy_rafal/20200706_Tormes/EC5_out_test_fasq_8/serotyping/serotyping.txt: No such file or directory
cp: cannot stat '/media/bioinformatyka/Documents/roboczy_rafal/20200706_Tormes/EC5_out_test_fasq_8/antibiotic_resistance_genes/*/*tab': No such file or directory
cp: cannot stat '/media/bioinformatyka/Documents/roboczy_rafal/20200706_Tormes/EC5_out_test_fasq_8/virulence_genes/*tab': No such file or directory
cp: cannot stat '/media/bioinformatyka/Documents/roboczy_rafal/20200706_Tormes/EC5_out_test_fasq_8/point_mutations/*/*_PointFinder_results.txt': No such file or directory
ERROR: Can't open '/media/bioinformatyka/Documents/roboczy_rafal/20200706_Tormes/EC5_out_test_fasq_8/report_files/*resfinder_min90.tab' to summarize.
ERROR: Can't open '/media/bioinformatyka/Documents/roboczy_rafal/20200706_Tormes/EC5_out_test_fasq_8/report_files/*card_min90.tab' to summarize.
ERROR: Can't open '/media/bioinformatyka/Documents/roboczy_rafal/20200706_Tormes/EC5_out_test_fasq_8/report_files/*argannot_min90.tab' to summarize.
sed: preserving permissions for ‘/media/bioinformatyka/Documents/roboczy_rafal/20200706_Tormes/EC5_out_test_fasq_8/report_files/sedjvhr0Z’: Operation not permitted
sed: preserving permissions for ‘/media/bioinformatyka/Documents/roboczy_rafal/20200706_Tormes/EC5_out_test_fasq_8/report_files/sed42WdP3’: Operation not permitted
sed: preserving permissions for ‘/media/bioinformatyka/Documents/roboczy_rafal/20200706_Tormes/EC5_out_test_fasq_8/report_files/sedwfVdN1’: Operation not permitted
sed: preserving permissions for ‘/media/bioinformatyka/Documents/roboczy_rafal/20200706_Tormes/EC5_out_test_fasq_8/report_files/sedY9FRy5’: Operation not permitted
sed: preserving permissions for ‘/media/bioinformatyka/Documents/roboczy_rafal/20200706_Tormes/EC5_out_test_fasq_8/report_files/sedjqnLE4’: Operation not permitted
sed: preserving permissions for ‘/media/bioinformatyka/Documents/roboczy_rafal/20200706_Tormes/EC5_out_test_fasq_8/report_files/sedW4M2W4’: Operation not permitted
sed: preserving permissions for ‘/media/bioinformatyka/Documents/roboczy_rafal/20200706_Tormes/EC5_out_test_fasq_8/report_files/sedbU8CC8’: Operation not permitted
sed: preserving permissions for ‘/media/bioinformatyka/Documents/roboczy_rafal/20200706_Tormes/EC5_out_test_fasq_8/report_files/sed2iWrG7’: Operation not permitted
sed: preserving permissions for ‘/media/bioinformatyka/Documents/roboczy_rafal/20200706_Tormes/EC5_out_test_fasq_8/report_files/sedmpg1ia’: Operation not permitted
sed: preserving permissions for ‘/media/bioinformatyka/Documents/roboczy_rafal/20200706_Tormes/EC5_out_test_fasq_8/report_files/sed5Um638’: Operation not permitted
sed: preserving permissions for ‘/media/bioinformatyka/Documents/roboczy_rafal/20200706_Tormes/EC5_out_test_fasq_8/report_files/sed7RzBwd’: Operation not permitted
sed: preserving permissions for ‘/media/bioinformatyka/Documents/roboczy_rafal/20200706_Tormes/EC5_out_test_fasq_8/report_files/sedyXv1mb’: Operation not permitted
sed: preserving permissions for ‘/media/bioinformatyka/Documents/roboczy_rafal/20200706_Tormes/EC5_out_test_fasq_8/report_files/sedLw9Eaf’: Operation not permitted
sed: preserving permissions for ‘/media/bioinformatyka/Documents/roboczy_rafal/20200706_Tormes/EC5_out_test_fasq_8/report_files/sed8SaZee’: Operation not permitted
sed: preserving permissions for ‘/media/bioinformatyka/Documents/roboczy_rafal/20200706_Tormes/EC5_out_test_fasq_8/report_files/sedHtkWve’: Operation not permitted
cut: '/media/bioinformatyka/Documents/roboczy_rafal/20200706_Tormes/EC5_out_test_fasq_8/report_files/*resfinder_min90.tab': No such file or directory
cut: /media/bioinformatyka/Documents/roboczy_rafal/20200706_Tormes/EC5_out_test_fasq_8/report_files/tmp2.txt: No such file or directory
paste: /media/bioinformatyka/Documents/roboczy_rafal/20200706_Tormes/EC5_out_test_fasq_8/report_files/tmp2.txt: No such file or directory
sed: preserving permissions for ‘/media/bioinformatyka/Documents/roboczy_rafal/20200706_Tormes/EC5_out_test_fasq_8/report_files/sedx1IG4i’: Operation not permitted
cp: cannot stat '/media/bioinformatyka/Documents/roboczy_rafal/20200706_Tormes/EC5_out_test_fasq_8/fimH_typing/fimH_typing.txt': No such file or directory
cp: cannot stat '/media/bioinformatyka/Documents/roboczy_rafal/20200706_Tormes/EC5_out_test_fasq_8/serotyping/serotyping.txt': No such file or directory
cp: cannot stat '/media/bioinformatyka/Documents/roboczy_rafal/20200706_Tormes/EC5_out_test_fasq_8/plasmids/*tab': No such file or directory
chmod: changing permissions of '/media/bioinformatyka/Documents/roboczy_rafal/20200706_Tormes/EC5_out_test_fasq_8/render_report.sh': Operation not permitted
Warning message:
package ‘rmarkdown’ was built under R version 3.6.3 

processing file: tormes_report.Rmd

  |                                                                            
  |                                                                      |   0%
  |                                                                            
  |..                                                                    |   3%
  ordinary text without R code

  |                                                                            
  |....                                                                  |   5%
label: unnamed-chunk-1 (with options) 
List of 3
 $ echo   : logi FALSE
 $ message: logi FALSE
 $ warning: logi FALSE

Registered S3 method overwritten by 'treeio':
  method     from
  root.phylo ape 
ggtree v2.0.4  For help: https://yulab-smu.github.io/treedata-book/

If you use ggtree in published research, please cite the most appropriate paper(s):

[36m-[39m Guangchuang Yu, Tommy Tsan-Yuk Lam, Huachen Zhu, Yi Guan. Two methods for mapping and visualizing associated data on phylogeny using ggtree. Molecular Biology and Evolution 2018, 35(12):3041-3043. doi: 10.1093/molbev/msy194
[36m-[39m Guangchuang Yu, David Smith, Huachen Zhu, Yi Guan, Tommy Tsan-Yuk Lam. ggtree: an R package for visualization and annotation of phylogenetic trees with their covariates and other associated data. Methods in Ecology and Evolution 2017, 8(1):28-36, doi:10.1111/2041-210X.12628

Attaching package: 'plotly'

The following object is masked from 'package:ggplot2':

    last_plot

The following object is masked from 'package:stats':

    filter

The following object is masked from 'package:graphics':

    layout

treeio v1.10.0  For help: https://yulab-smu.github.io/treedata-book/

If you use treeio in published research, please cite:

LG Wang, TTY Lam, S Xu, Z Dai, L Zhou, T Feng, P Guo, CW Dunn, BR Jones, T Bradley, H Zhu, Y Guan, Y Jiang, G Yu. treeio: an R package for phylogenetic tree input and output with richly annotated and associated data. Molecular Biology and Evolution 2019, accepted. doi: 10.1093/molbev/msz240

  |                                                                            
  |......                                                                |   8%
  ordinary text without R code

  |                                                                            
  |........                                                              |  11%
label: unnamed-chunk-2 (with options) 
List of 1
 $ echo: logi FALSE

  |                                                                            
  |.........                                                             |  14%
  ordinary text without R code

  |                                                                            
  |...........                                                           |  16%
label: unnamed-chunk-3 (with options) 
List of 1
 $ echo: logi FALSE

Quitting from lines 75-78 (tormes_report.Rmd) 
Error in read.table("sequencing_assembly_report.txt", header = T, sep = "\t",  : 
  no lines available in input
Calls: <Anonymous> ... withCallingHandlers -> withVisible -> eval -> eval -> read.table
In addition: Warning messages:
1: package 'ggplot2' was built under R version 3.6.3 
2: package 'knitr' was built under R version 3.6.3 
3: package 'plotly' was built under R version 3.6.3 
4: package 'RColorBrewer' was built under R version 3.6.3 
5: package 'reshape2' was built under R version 3.6.3 

Execution halted

**Comment by biobrad** [comment]
Hey mate,

Looks like you are running it from root. Try running it again but use sudo
before the tormes commands. If that doesn't work you should try installing
everything under your username ie: /home/yourusername/
I have anaconda and everything installed there. Running stuff from root is
a pain with permissions etc.
Cheers
Brad

**Comment by nmquijada** [comment]
Dear @Stigimoloch 
As @biobrad said, it seems that you have a problem with permissions. Do you have permissions from the directory where you run tormes and where you set the output directory?
Best,
Narciso
