### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by SrivastavaM** [nmquijada/tormes#58]
Hi want to use Tormes pipeline

I getting following error during installation

```
(base) m23445@108:~/tormes$ conda env create -n tormes-1.3.0 --file tormes-1.3.0.yml
Collecting package metadata (repodata.json): failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/opt/anaconda/lib/python3.7/site-packages/urllib3/response.py", line 700, in _update_chunk_length
        self.chunk_left = int(line, 16)
    ValueError: invalid literal for int() with base 16: b''

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/opt/anaconda/lib/python3.7/site-packages/urllib3/response.py", line 441, in _error_catcher
        yield
      File "/opt/anaconda/lib/python3.7/site-packages/urllib3/response.py", line 767, in read_chunked
        self._update_chunk_length()
      File "/opt/anaconda/lib/python3.7/site-packages/urllib3/response.py", line 704, in _update_chunk_length
        raise InvalidChunkLength(self, line)
    urllib3.exceptions.InvalidChunkLength: InvalidChunkLength(got length b'', 0 bytes read)

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/opt/anaconda/lib/python3.7/site-packages/requests/models.py", line 816, in generate
        yield from self.raw.stream(chunk_size, decode_content=True)
      File "/opt/anaconda/lib/python3.7/site-packages/urllib3/response.py", line 575, in stream
        for line in self.read_chunked(amt, decode_content=decode_content):
      File "/opt/anaconda/lib/python3.7/site-packages/urllib3/response.py", line 796, in read_chunked
        self._original_response.close()
      File "/opt/anaconda/lib/python3.7/contextlib.py", line 130, in __exit__
        self.gen.throw(type, value, traceback)
      File "/opt/anaconda/lib/python3.7/site-packages/urllib3/response.py", line 458, in _error_catcher
        raise ProtocolError("Connection broken: %r" % e, e)
    urllib3.exceptions.ProtocolError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/opt/anaconda/lib/python3.7/site-packages/conda/exceptions.py", line 1114, in __call__
        return func(*args, **kwargs)
      File "/opt/anaconda/lib/python3.7/site-packages/conda_env/cli/main.py", line 80, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/opt/anaconda/lib/python3.7/site-packages/conda_env/cli/main_create.py", line 143, in execute
        result[installer_type] = installer.install(prefix, pkg_specs, args, env)
      File "/opt/anaconda/lib/python3.7/site-packages/conda_env/installers/conda.py", line 51, in install
        prune=getattr(args, 'prune', False), update_modifier=UpdateModifier.FREEZE_INSTALLED)
      File "/opt/anaconda/lib/python3.7/site-packages/conda/core/solve.py", line 155, in solve_for_transaction
        should_retry_solve)
      File "/opt/anaconda/lib/python3.7/site-packages/conda/core/solve.py", line 196, in solve_for_diff
        force_remove, should_retry_solve)
      File "/opt/anaconda/lib/python3.7/site-packages/conda/core/solve.py", line 300, in solve_final_state
        ssc = self._collect_all_metadata(ssc)
      File "/opt/anaconda/lib/python3.7/site-packages/conda/common/io.py", line 86, in decorated
        return f(*args, **kwds)
      File "/opt/anaconda/lib/python3.7/site-packages/conda/core/solve.py", line 463, in _collect_all_metadata
        index, r = self._prepare(prepared_specs)
      File "/opt/anaconda/lib/python3.7/site-packages/conda/core/solve.py", line 1059, in _prepare
        self.subdirs, prepared_specs, self._repodata_fn)
      File "/opt/anaconda/lib/python3.7/site-packages/conda/core/index.py", line 288, in get_reduced_index
        repodata_fn=repodata_fn)
      File "/opt/anaconda/lib/python3.7/site-packages/conda/core/subdir_data.py", line 139, in query_all
        result = tuple(concat(executor.map(subdir_query, channel_urls)))
      File "/opt/anaconda/lib/python3.7/concurrent/futures/_base.py", line 598, in result_iterator
        yield fs.pop().result()
      File "/opt/anaconda/lib/python3.7/concurrent/futures/_base.py", line 428, in result
        return self.__get_result()
      File "/opt/anaconda/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
        raise self._exception
      File "/opt/anaconda/lib/python3.7/concurrent/futures/thread.py", line 57, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/opt/anaconda/lib/python3.7/site-packages/conda/core/subdir_data.py", line 132, in <lambda>
        package_ref_or_match_spec))
      File "/opt/anaconda/lib/python3.7/site-packages/conda/core/subdir_data.py", line 144, in query
        self.load()
      File "/opt/anaconda/lib/python3.7/site-packages/conda/core/subdir_data.py", line 209, in load
        _internal_state = self._load()
      File "/opt/anaconda/lib/python3.7/site-packages/conda/core/subdir_data.py", line 378, in _load
        repodata_fn=self.repodata_fn)
      File "/opt/anaconda/lib/python3.7/site-packages/conda/core/subdir_data.py", line 701, in fetch_repodata_remote_request
        timeout=timeout)
      File "/opt/anaconda/lib/python3.7/site-packages/requests/sessions.py", line 600, in get
        return self.request("GET", url, **kwargs)
      File "/opt/anaconda/lib/python3.7/site-packages/requests/sessions.py", line 587, in request
        resp = self.send(prep, **send_kwargs)
      File "/opt/anaconda/lib/python3.7/site-packages/requests/sessions.py", line 745, in send
        r.content
      File "/opt/anaconda/lib/python3.7/site-packages/requests/models.py", line 899, in content
        self._content = b"".join(self.iter_content(CONTENT_CHUNK_SIZE)) or b""
      File "/opt/anaconda/lib/python3.7/site-packages/requests/models.py", line 818, in generate
        raise ChunkedEncodingError(e)
    requests.exceptions.ChunkedEncodingError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))

`$ /opt/anaconda/bin/conda-env create -n tormes-1.3.0 --file tormes-1.3.0.yml`

  environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/opt/anaconda/bin/conda
             CONDA_PREFIX=/opt/anaconda
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/opt/anaconda/bin/python
               CONDA_ROOT=/opt/anaconda
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
                     PATH=/opt/anaconda/bin:/home/m23445/.local/bin:/home/m23445/bin:/opt/anacon
                          da/bin:/opt/anaconda/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin
                          :/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/opt/biotoo
                          ls/bin:/home/m23445/JIGV/jigv-0.1.7:/home/m23445/spades/SPAdes-3.15.4-
                          Linux/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /opt/anaconda
            shell level : 1
       user config file : /home/m23445/.condarc
 populated config files : /home/m23445/.condarc
          conda version : 4.13.0
    conda-build version : 3.21.7
         python version : 3.7.12.final.0
       virtual packages : __linux=5.4.0=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /opt/anaconda  (read only)
      conda av data dir : /opt/anaconda/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/anaconda/pkgs
                          /home/m23445/.conda/pkgs
       envs directories : /home/m23445/.conda/envs
                          /opt/anaconda/envs
               platform : linux-64
             user-agent : conda/4.13.0 requests/2.28.1 CPython/3.7.12 Linux/5.4.0-110-generic ubuntu/20.04.4 glibc/2.31
                UID:GID : 1011:1012
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.
```
Can you please let me know what is the problem?

Thanks

**Comment by nmquijada** [comment]
Hi @SrivastavaM 

I am afraid you are having issues with python not related to tormes.

It would be a bit challenging for me to help you here, but let's see if we find an alternative solution.
Just to check that your conda (anaconda) installation is working properly, have you been able to install and/or create other environments by using ```conda env create``` or ```conda create```?

Thanks,
Narciso

**Comment by SrivastavaM** [comment]
Thanks, I updated my conda and run the following
`conda env create -f tormes-1.3.0.yml`
It worked.

**Comment by SrivastavaM** [comment]
Thanks, I updated my conda and run the following
`conda env create -f tormes-1.3.0.yml`
It worked.

**Comment by nmquijada** [comment]
Good to know!
Thanks for the update.

Narciso
